###
# Should return itself and do insert
POST https://matquiz.dk/ServerStorage/storageAPI.php HTTP/1.1
Content-Type: application/json
Authorization: 1234

{"page":"ServerStorage", "key":"httpTest1", "value":"2"}

###
# Should return key, value and page if post is run first
GET https://matquiz.dk/ServerStorage/storageAPI.php?key=httpTest1&page=ServerStorage HTTP/1.1
Content-Type: application/json
Authorization: 1234

### 
# Should return 204 or 404.
DELETE https://matquiz.dk/ServerStorage/storageAPI.php HTTP/1.1
Content-Type: application/json
Authorization: 1234

{"page":"ServerStorage", "key":"httpTest1"}

### 
# Should clear resource and return 204 or 404.
DELETE https://matquiz.dk/ServerStorage/storageAPI.php HTTP/1.1
Content-Type: application/json
Authorization: 1234

{"page":"ServerStorage"}
